include:
  - ./network.yaml
  - ./vaultwarden/docker-compose.yaml
  - ./tuwunel/docker-compose.yaml
  - ./turn/docker-compose.yaml
  - ./livekit/docker-compose.yaml
  - ./nginx/docker-compose.yaml
  - ./timescaledb/docker-compose.yaml
  - ./grafana/docker-compose.yaml
  - ./transmission/docker-compose.yaml
  - ./jellyfin/docker-compose.yaml
  - ./media-automation/docker-compose.yaml
  - ./dns/docker-compose.yaml
  #  - ./adguard-unbound/docker-compose.yaml
  - ./webdav/docker-compose.yaml
