services:
  conduit:
    image: matrixconduit/matrix-conduit:latest
    container_name: conduit
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/matrix-conduit/
      - ./conduit.toml:/etc/conduit.toml:ro   # монтируем конфиг
    environment:
      - CONDUIT_CONFIG=/etc/conduit.toml

    networks:
      - main-net
