services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ${HOME}/.acme.sh:/etc/ssl/turn:ro
    command: [ "--log-file=stdout", "--static-auth-secret=${TURN_SERVER_TOKEN}" ]