services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/serial/by-id/usb-Zigbee_Dongle_Dongle-PMG24_f633ebea3b5ef011af8353401045c30f-if00-port0:/dev/ttyUSB0
#    networks:
#      - main-net