services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - ./vaultwarden_data:/data
    environment:
      - DOMAIN=https://${VAULTWARDEN_DOMAIN}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}  # Для админ-панели
      #- SIGNUPS_ALLOWED=false                # Запретить публичную регистрацию
      - WEBSOCKET_ENABLED=true     # Включить WebSocket
      - WEBSOCKET_ADDRESS=0.0.0.0  # Слушать все интерфейсы

    networks:
      - main-net
